services:
  ml-service:
    build:
      context: ./ml-service
      # cache_from: (hilangin aja komentarnya kalo ga mau build image baru)
      #   - ml-service:latest (sama ini)
    image: ml-service:latest
    container_name: ml_service
    ports:
      - "8000:8000"
    volumes:
      - whisper_data:/app/output_transcriptions
      - predictions_data:/app/output_predictions
      - whisper_model_cache:/root/.cache/whisper
      - hf_cache:/root/.cache/huggingface
    environment:
      - TZ=Asia/Jakarta
    restart: unless-stopped

volumes:
  whisper_data:
  whisper_model_cache:
  predictions_data:
  hf_cache: